*  PANDA   = Library to handle dataframe (row , column )
*  NUMPY   = to handle ND array  (matrix) 
*  SEBORN  = statistical visualization
*  SCIPY    = use for scientific python library

# NumPy (Numerical Python)

In [14]:
# Library used to handle N-dimensional arrays (ndarray).
# collection of data data structure + math + array
# library or package which handle N-Dimentional array or multy dimentional array (1d,2d,3d,..Nd)
# It is a powerful library used for numerical computing, especially in Data Science, Machine Learning, and Scientific Computing.
# By default, NumPy creates float arrays, but we can change it to int or other types."
 # use :--
    # arithmatic 
    # stastistical
    # bitwise
    # copy & view array 
    # matrix operation
    # linear algebra
    # stacking
    # broadcasting 
    # math operation 
    #sorting , searching

# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and 
  # it will be converted into an ndarray:


# Why is NumPy Faster Than Lists?
        # NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
        # This behavior is called locality of reference in computer science.
        # This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Which Language is NumPy written in?
       # NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

# Dimensions in Arrays
   # A dimension in arrays is one level of array depth (nested arrays).

In [16]:
            # package = collection of  module 
            # module = collection of  function
            # function = collection of  statement 
    
            ## two type of fun :--- 
    
                # inbuilt fun =        print() , max(), min(), len(), id(),....
                # user define fun =    alwase asign with ( def ) keyword


In [17]:
import numpy as np

In [18]:
np.__version__

'2.3.5'

In [19]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

## Creating Arrays

In [21]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [22]:
type(my_list)

list

In [23]:
arr = np.array(my_list)

In [24]:
arr

array([0, 1, 2, 3, 4, 5])

In [25]:
type(arr)

numpy.ndarray

In [26]:
type(my_list)

list

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.arange(3.0)   # 3.0 (a float), NumPy automatically creates a float array:

array([0., 1., 2.])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
np.arange(20,10)   # 1st arg < 2nd arg

array([], dtype=int64)

In [36]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [37]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [38]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [40]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [46]:
ar = np.arange(-30,20)

In [47]:
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [48]:
type(ar)

numpy.ndarray

In [49]:
np.arange(10,10)

array([], dtype=int64)

In [50]:
np.arange()

TypeError: arange() requires stop to be specified.

In [51]:
np.arange(10,30,5)  # [ start=10 ,  stop= 30 ,  step=5 ]

array([10, 15, 20, 25])

In [52]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [53]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [57]:
np.zeros(3)  # parameter tunning (np.zeros() creates an array filled with 0 values.)

array([0., 0., 0.])

In [58]:
np.zeros(5,dtype=int)  # hyper parameter tunning  (by default numpy create float dtype so we can change)

array([0, 0, 0, 0, 0])

In [62]:
np.zeros((6,5), dtype=int)  # 6 = row & 5 = column

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [63]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [64]:
zero = np.zeros([2,3])
print(zero)

print('####')

print(type(zero))

[[0. 0. 0.]
 [0. 0. 0.]]
####
<class 'numpy.ndarray'>


In [65]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [67]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [68]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.zeros((10,30))      # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [72]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
n =(6,7)
n1 = (6,8)
print(np.zeros(n1))   # parameter tunnin

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 


[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [75]:
n

(6, 7)

In [76]:
n1

(6, 8)

In [77]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [78]:
print(n)

(6, 7)


In [79]:
np.zeros(n)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [83]:
np.ones(3)   # bydefault numpy give float value

array([1., 1., 1.])

In [84]:
np.ones(4 , dtype=int)

array([1, 1, 1, 1])

In [85]:
np.ones(4)

array([1., 1., 1., 1.])

In [86]:
n

(6, 7)

In [87]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [90]:
np.ones(n , dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [91]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [92]:
np.ones(2)

array([1., 1.])

In [93]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [95]:
range(5)

range(0, 5)

In [96]:
r = range(5)
r

range(0, 5)

In [98]:
for i in r:
    print(i)

0
1
2
3
4


In [99]:
list(range(5))

[0, 1, 2, 3, 4]

In [100]:
range(1,10)

range(1, 10)

In [101]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [102]:
list(range(1,10,3))

[1, 4, 7]

In [103]:
y = list(range(12))

In [104]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [105]:
rand(3,2)

NameError: name 'rand' is not defined

In [106]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [108]:
np.random.rand(5)    # Generates 5 random numbers

array([0.4721302 , 0.35950503, 0.51157068, 0.14872658, 0.20275162])

In [110]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [112]:
np.random.rand(2,4)  # Generates 2row & 4 column with random numbers

array([[0.51062532, 0.77882858, 0.86382075, 0.89554593],
       [0.24737701, 0.31820145, 0.48382805, 0.64348944]])

In [122]:
np.random.rand(2,4)

array([[0.12093797, 0.84100758, 0.91693731, 0.6711543 ],
       [0.10860041, 0.37454855, 0.98940016, 0.02677989]])

In [124]:
np.random.randint(2,4)  # it generates a random integer (low =2 , high =4)

3

In [126]:
np.random.rand(2,20)

array([[0.59713155, 0.52474765, 0.00556164, 0.27083349, 0.20672206,
        0.91185253, 0.70797828, 0.73241127, 0.73262709, 0.86940931,
        0.01715001, 0.6227873 , 0.11487421, 0.37369813, 0.33610099,
        0.69603857, 0.5094946 , 0.47013304, 0.14555635, 0.33733453],
       [0.04804186, 0.54523215, 0.41878367, 0.11011976, 0.8001698 ,
        0.19602622, 0.35375965, 0.50499499, 0.7750275 , 0.27586541,
        0.57145237, 0.74082049, 0.3244954 , 0.4007128 , 0.22317947,
        0.22073154, 0.06501677, 0.99882458, 0.72865562, 0.75225015]])

In [130]:
np.random.randint(2,20)    # it generates a random integer (low =2 , high =20)

17

In [131]:
np.random.randint(0,1) 

0

In [137]:
np.random.randint(10,20,5) 
# low = 10 → start (included)
# high = 20 → stop (NOT included)
# size = 5 → generate 5 random numbers

array([11, 13, 10, 13, 15], dtype=int32)

In [136]:
np.random.randint(1,6,4)

array([4, 5, 4, 2], dtype=int32)

In [138]:
np.random.rand(3)

array([0.6525727 , 0.646594  , 0.31035046])

In [139]:
np.random.randint(1)  

0

In [140]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [141]:
np.random.randint(-30,20,10) 

array([-19,   3, -26,  -2,  -2, -10, -24, -20,  -6, -26], dtype=int32)

In [142]:
np.random.randint(20,30,10) 

array([27, 22, 28, 20, 26, 24, 28, 23, 25, 22], dtype=int32)

In [143]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

5

In [144]:
np.random.randint(10,21,3)

array([15, 12, 10], dtype=int32)

In [145]:
np.random.randint(1,12,10)

array([ 3, 11,  5,  2,  5,  4,  8, 11,  7,  9], dtype=int32)

In [147]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtrix

# 10 → start (included)
# 40 → stop (NOT included)
# (10,10) → shape (10 rows × 10 columns)

array([[31, 35, 15, 30, 27, 18, 29, 11, 37, 31],
       [34, 24, 29, 21, 21, 33, 12, 30, 33, 35],
       [30, 31, 27, 25, 39, 32, 30, 29, 25, 38],
       [32, 21, 33, 27, 27, 27, 29, 13, 28, 28],
       [34, 29, 36, 18, 21, 20, 21, 37, 28, 38],
       [39, 23, 30, 24, 10, 30, 21, 25, 34, 26],
       [11, 26, 10, 18, 30, 16, 11, 27, 20, 11],
       [25, 33, 30, 21, 20, 31, 31, 21, 39, 30],
       [22, 32, 14, 27, 13, 38, 13, 34, 20, 13],
       [18, 33, 34, 35, 15, 21, 20, 19, 12, 24]], dtype=int32)

In [148]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[71,  8, 57,  4, 59, 19, 14, 86, 30, 23, 90, 60],
       [55, 78, 73, 98, 72, 66, 83, 85, 67, 68, 87, 53],
       [24, 36, 35, 44,  2, 69, 97, 91, 72, 94, 80, 36],
       [62, 38,  7, 63, 50, 50, 90, 66, 64, 48, 50, 62],
       [86,  7, 81, 82, 66, 26,  4, 74, 71, 64, 89, 99],
       [81, 28, 75, 86, 43, 43, 23, 62, 34, 42, 22, 36],
       [ 8, 12,  1, 89, 36, 34, 75, 13, 91, 44, 52, 73],
       [16, 62, 52, 59, 75, 17, 33, 17, 97, 38, 29, 45],
       [44, 62, 31, 46, 90, 26, 86, 43, 20, 25, 12, 96],
       [36, 11, 83, 74, 80, 66, 73, 59, 91, 80, 95, 67],
       [20, 44, 45, 69, 54, 54, 58, 74, 65, 92,  9, 29],
       [88, 43, 75, 41, 23, 76, 76, 28, 27, 85, 71, 67]], dtype=int32)

In [151]:
# reshape  =  Reshape works only if the total number of elements matches the new shape."

In [150]:
np.arange(1,13).reshape(3,4) # Starts from 1, Stops before 13 & reshape (3,4 =row & column)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [158]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [159]:
type(b)

numpy.ndarray

In [160]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [161]:
b[:]

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [166]:
b[1:3]

array([[18, 11, 10, 11],
       [18, 16, 13, 18]], dtype=int32)

In [167]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [169]:
b[1,2]

np.int32(10)

In [170]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [171]:
b[1,3]

np.int32(11)

In [173]:
b[1,-1]  # row & column [ , ]

np.int32(11)

In [174]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [180]:
b[2:3]  # slicing [ : ]

array([[18, 16, 13, 18]], dtype=int32)

In [181]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [182]:
b[0:-2]

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18]], dtype=int32)

In [183]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [184]:
b[0,2]

np.int32(13)

In [185]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [186]:
b[-5,-3]

np.int32(18)

In [187]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [188]:
b[-4,2]

np.int32(10)

In [200]:
np.random.randint(10,20,(4,4))

array([[13, 11, 10, 19],
       [18, 18, 19, 14],
       [16, 16, 14, 14],
       [19, 10, 13, 19]], dtype=int32)

In [201]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [202]:
b[-4,-2]

np.int32(10)

In [203]:
b

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [204]:
b[:]

array([[13, 18, 13, 12],
       [18, 11, 10, 11],
       [18, 16, 13, 18],
       [19, 11, 10, 14],
       [19, 19, 12, 12]], dtype=int32)

In [205]:
b[-4,2]

np.int32(10)

## Numpy Operations

In [207]:
a = np.random.randint(10,20,10)
a

array([11, 19, 13, 15, 14, 14, 16, 19, 13, 14], dtype=int32)

In [208]:
id(a)

1700234156272

In [209]:
arr

array([0, 1, 2, 3, 4, 5])

In [213]:
arr2 = np.random.randint(0,100,(10,10))

In [214]:
arr2

array([[89, 60, 36, 77, 46, 32, 36,  0, 34, 88],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37],
       [85,  8, 97, 28, 48, 19, 60, 81, 56, 93],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [40, 35, 47,  1,  8, 15,  3, 70,  0, 54],
       [ 2, 50, 48, 80, 37, 57, 61, 97, 19, 53],
       [51, 47, 15,  7, 98, 33, 52, 21, 59,  3],
       [25, 80, 52, 45, 56, 12, 33, 19, 12, 91],
       [64, 85, 89, 43, 65, 38, 21,  1, 89, 70],
       [84, 79, 86, 63, 41, 80, 61, 24, 57, 77]], dtype=int32)

In [215]:
arr

array([0, 1, 2, 3, 4, 5])

In [216]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [217]:
arr[:4]

array([0, 1, 2, 3])

In [218]:
arr2[:]

array([[89, 60, 36, 77, 46, 32, 36,  0, 34, 88],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37],
       [85,  8, 97, 28, 48, 19, 60, 81, 56, 93],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [40, 35, 47,  1,  8, 15,  3, 70,  0, 54],
       [ 2, 50, 48, 80, 37, 57, 61, 97, 19, 53],
       [51, 47, 15,  7, 98, 33, 52, 21, 59,  3],
       [25, 80, 52, 45, 56, 12, 33, 19, 12, 91],
       [64, 85, 89, 43, 65, 38, 21,  1, 89, 70],
       [84, 79, 86, 63, 41, 80, 61, 24, 57, 77]], dtype=int32)

In [219]:
arr2[0:5]

array([[89, 60, 36, 77, 46, 32, 36,  0, 34, 88],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37],
       [85,  8, 97, 28, 48, 19, 60, 81, 56, 93],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [40, 35, 47,  1,  8, 15,  3, 70,  0, 54]], dtype=int32)

In [220]:
arr2

array([[89, 60, 36, 77, 46, 32, 36,  0, 34, 88],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37],
       [85,  8, 97, 28, 48, 19, 60, 81, 56, 93],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [40, 35, 47,  1,  8, 15,  3, 70,  0, 54],
       [ 2, 50, 48, 80, 37, 57, 61, 97, 19, 53],
       [51, 47, 15,  7, 98, 33, 52, 21, 59,  3],
       [25, 80, 52, 45, 56, 12, 33, 19, 12, 91],
       [64, 85, 89, 43, 65, 38, 21,  1, 89, 70],
       [84, 79, 86, 63, 41, 80, 61, 24, 57, 77]], dtype=int32)

In [222]:
arr2[1,4]

np.int32(51)

In [223]:
arr2[-5,5]

np.int32(57)

In [224]:
arr2[-5,-5]

np.int32(57)

In [225]:
arr2[-1,-2]

np.int32(57)

In [226]:
arr2[::-1]

array([[84, 79, 86, 63, 41, 80, 61, 24, 57, 77],
       [64, 85, 89, 43, 65, 38, 21,  1, 89, 70],
       [25, 80, 52, 45, 56, 12, 33, 19, 12, 91],
       [51, 47, 15,  7, 98, 33, 52, 21, 59,  3],
       [ 2, 50, 48, 80, 37, 57, 61, 97, 19, 53],
       [40, 35, 47,  1,  8, 15,  3, 70,  0, 54],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [85,  8, 97, 28, 48, 19, 60, 81, 56, 93],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37],
       [89, 60, 36, 77, 46, 32, 36,  0, 34, 88]], dtype=int32)

In [227]:
arr2[::-2]

array([[84, 79, 86, 63, 41, 80, 61, 24, 57, 77],
       [25, 80, 52, 45, 56, 12, 33, 19, 12, 91],
       [ 2, 50, 48, 80, 37, 57, 61, 97, 19, 53],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37]], dtype=int32)

In [229]:
arr2

array([[89, 60, 36, 77, 46, 32, 36,  0, 34, 88],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37],
       [85,  8, 97, 28, 48, 19, 60, 81, 56, 93],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [40, 35, 47,  1,  8, 15,  3, 70,  0, 54],
       [ 2, 50, 48, 80, 37, 57, 61, 97, 19, 53],
       [51, 47, 15,  7, 98, 33, 52, 21, 59,  3],
       [25, 80, 52, 45, 56, 12, 33, 19, 12, 91],
       [64, 85, 89, 43, 65, 38, 21,  1, 89, 70],
       [84, 79, 86, 63, 41, 80, 61, 24, 57, 77]], dtype=int32)

In [230]:
arr2[::-3]

array([[84, 79, 86, 63, 41, 80, 61, 24, 57, 77],
       [51, 47, 15,  7, 98, 33, 52, 21, 59,  3],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [89, 60, 36, 77, 46, 32, 36,  0, 34, 88]], dtype=int32)

In [231]:
arr2

array([[89, 60, 36, 77, 46, 32, 36,  0, 34, 88],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37],
       [85,  8, 97, 28, 48, 19, 60, 81, 56, 93],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [40, 35, 47,  1,  8, 15,  3, 70,  0, 54],
       [ 2, 50, 48, 80, 37, 57, 61, 97, 19, 53],
       [51, 47, 15,  7, 98, 33, 52, 21, 59,  3],
       [25, 80, 52, 45, 56, 12, 33, 19, 12, 91],
       [64, 85, 89, 43, 65, 38, 21,  1, 89, 70],
       [84, 79, 86, 63, 41, 80, 61, 24, 57, 77]], dtype=int32)

In [232]:
arr2[:-3]

array([[89, 60, 36, 77, 46, 32, 36,  0, 34, 88],
       [79, 15, 19,  8, 51, 57, 53, 47, 36, 37],
       [85,  8, 97, 28, 48, 19, 60, 81, 56, 93],
       [79, 33, 20, 30, 32, 35, 98, 72, 95, 10],
       [40, 35, 47,  1,  8, 15,  3, 70,  0, 54],
       [ 2, 50, 48, 80, 37, 57, 61, 97, 19, 53],
       [51, 47, 15,  7, 98, 33, 52, 21, 59,  3]], dtype=int32)

In [234]:
arr2[-3:]

array([[25, 80, 52, 45, 56, 12, 33, 19, 12, 91],
       [64, 85, 89, 43, 65, 38, 21,  1, 89, 70],
       [84, 79, 86, 63, 41, 80, 61, 24, 57, 77]], dtype=int32)

In [235]:
arr

array([0, 1, 2, 3, 4, 5])

In [236]:
arr.max()

np.int64(5)

In [237]:
arr.min()

np.int64(0)

In [238]:
arr

array([0, 1, 2, 3, 4, 5])

In [239]:
arr.mean()

np.float64(2.5)

In [240]:
arr

array([0, 1, 2, 3, 4, 5])

In [241]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [243]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import* can you please find the median, mode

In [258]:
arr

array([0, 1, 2, 3, 4, 5])

In [259]:
arr.reshape(3,2)  # 3 row , 2 column

array([[0, 1],
       [2, 3],
       [4, 5]])

In [260]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [261]:
arr

array([0, 1, 2, 3, 4, 5])

In [262]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
# NumPy arrays are usually C-contiguous by default.

# order='c' :=
            # C → Computer → Row-wise  
            # 👉 order='C' means C-style order (Row-major order).
            # 👉 It fills the new array row by row.

        #  ex:= [1 2 3 4 5 6]  
        #          [[1 2 3]
        #          [4 5 6]]

# order='F' :=
            # F → Fortran → Column-wise
            # 👉 order='F' means Fortran-style order (Column-major order)
            # 👉 It fills the array column by column.

        #  ex:=  [1 2 3 4 5 6]
        #             [[1 3 5]
        #             [2 4 6]]

# order='A':= 
            # 'A' = “Adjust according to original memory layout”
            # 👉 order='A' means “Any” order
            # 👉It depends on how the array is stored in memory.
            #  If the array is stored in order:C (row-major) then it behaves like 'C'
            #  If the array is stored in order:f (column-major) then it behaves like 'f'


# Difference Between 'C' and 'F'

        # | Order | Meaning       | Filling Style                         |
        # | ----- | ------------- | -----------------------------------   |
        # | `'C'` | C-style       | Row-wise                              |
        # | `'F'` | Fortran-style | Column-wise                           |
        # | `'A'` |  Automatic    | Uses array’s existing memory order    |

In [269]:
arr.reshape(2,3,order='c')   # order='C' means C-style order (Row-major order).

array([[0, 1, 2],
       [3, 4, 5]])

In [270]:
arr.reshape(2,3,order='F')   # order='F' means Fortran-style order (Column-major order)

array([[0, 2, 4],
       [1, 3, 5]])

In [271]:
arr.reshape(2,3,order='A')  # order='A' almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [272]:
arr

array([0, 1, 2, 3, 4, 5])

In [273]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [275]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [276]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [277]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [278]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [279]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [281]:
arr

array([0, 1, 2, 3, 4, 5])

In [282]:
ar.reshapr(3,2)

AttributeError: 'numpy.ndarray' object has no attribute 'reshapr'

## Indexing

In [286]:
mat = np.arange(0,100).reshape(10,10)

In [287]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [288]:
row =4
col =5

In [289]:
col

5

In [290]:
row

4

In [291]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [293]:
mat[row,col]

np.int64(45)

In [294]:
mat[4,5]

np.int64(45)

In [295]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [296]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [310]:
col=6

In [311]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [312]:
mat[6]      # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [313]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
 #  slices :=  
            #    1} array [row_start : row_stop : row_step , col_start : col_stop : col_step]
            #    2} array[row_start:row_stop , col_start:col_stop]

#  [ , ]  = ' , '  means row and col
# [ : ]  =  ' : '  means slices  

In [314]:
# With Slices

mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [315]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [316]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [317]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [329]:
mat[: ,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [319]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [337]:
mat[:col]        # [ row-start: row-stop ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [338]:
mat[:col, 2:4]            # [row-start: row-stop , col-start:col-stop , step ]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [339]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [340]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [341]:
row

4

In [342]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [343]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [344]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [345]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [346]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [347]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [349]:
mat[: , 8]   # col 8

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [350]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [351]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [352]:
row

4

In [353]:
col

6

In [357]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [358]:
mat[:,col:9] 

array([[ 6,  7,  8],
       [16, 17, 18],
       [26, 27, 28],
       [36, 37, 38],
       [46, 47, 48],
       [56, 57, 58],
       [66, 67, 68],
       [76, 77, 78],
       [86, 87, 88],
       [96, 97, 98]])

In [360]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [361]:
mat[1,4]

np.int64(14)

In [364]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [365]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [366]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [367]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [368]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [369]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [370]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [371]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [372]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [373]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [374]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [375]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [376]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [377]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [378]:
mat[:4]   # [start : stop 4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [380]:
mat[4:]   # [start 4 : stop ]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [382]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [383]:
mat[::-3]   # [ start : stop : step -3 ]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [384]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [385]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [386]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [387]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [390]:
mat[2:6,2:4]    # row [start-2 : stop 6]    and [,]   column [start-2 : stop 4 ]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [391]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [394]:
mat[0,1]     # row 0 and col 1

np.int64(1)

In [395]:
mat[1,6]

np.int64(16)

In [396]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [397]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [398]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [399]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [400]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [401]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [402]:
mat[3,5]

np.int64(35)

In [403]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [404]:
mat[1:2,2:4] 

array([[12, 13]])

In [405]:
mat[2:3,2:3] 

array([[22]])

In [406]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [407]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [408]:
mat[2:3,4:5]

array([[24]])

# Masking

In [410]:
mat          # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [411]:
id(mat)

1700237883216

In [412]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [413]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [414]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [416]:
mat > 50   # greater than 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
    #  | Expression       |    Meaning                   |
    #  | ---------------- |   -------------------------  |
    #  | `mat == 50`      |   Creates True/False matrix  |
    #  | `mat[mat == 50]` |   Extracts only 50 values   |


In [420]:
mat[mat==50]      # Extracts only 50 values 

array([50])

In [421]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [422]:
mat == 50   #  Creates True/False matrix

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [425]:
a1 = mat[mat<50]    # less than 50
a1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [426]:
a2 = mat[mat>50]    # greater than 50
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [429]:
a3 = mat[mat<=50]       # less than 50 or = 50
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [430]:
a3 = mat[mat>=50]         # greater than 50  0r = 50
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [431]:
a4 = mat[mat==50]
a4

array([50])

# python program to generat otp 

In [442]:
import random

def generate_otp(length=4):      # Creates a function with default OTP length = 4.
    """Generate a numeric OTP of a specified length."""
    
    digits = '012345'      # This will generate OTP using only digits:
    otp = ''.join(random.choice(digits) for _ in range(length))   # Joins them into one string
    
    return otp


otp_length = 4  # Creates a function with OTP length = 4.

otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")



Your OTP is: 3354


In [444]:
def wish():
    print('good even')
wish()
def wish():
    print('good even')
wish()
def wish():
    print('good even')
wish()


good even
good even
good even


In [445]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [447]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000018BDEA64EC0>


In [448]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
