*  PANDA   = Library to handle dataframe (row , column )
*  NUMPY   = to handle ND array  (matrix) 
*  SEABORN  = statistical visualization
*  SCIPY    = use for scientific python library

# Complete NUMPY DOCUMENTATION

![uses_numpy](http://localhost:8888/tree/Prakash%20sir%20practical/Assignment/uses_numpy.jpeg)


# 1. Array Creation Functions

In [1]:
import numpy as np

In [14]:
a = np.array([1,2,3])      # Create an array from a list(- np.arange(start, stop, step) → you specify the step size)
print("Array a:" , a)

Array a: [1 2 3]


In [7]:
# Create an array with evenly spaced values 
b = np.arange(0,10,2)     # Values from 0 to 10 with step 2
print("Array b:" , b)

Array b: [0 2 4 6 8]


In [11]:
# Create an array with linearly spaced values
c = np.linspace(0,1,5)     # 5 values evenly spaced between 0 and 1 ( np.linspace(start, stop, num) → you specify the number of points)
print("Array c:" , c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [18]:
# Create an array filled with zeros
d = np.zeros((2, 3))  # 2x3 array of "zeros"
print("Array d:\n" , d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3 x 2  array of "ones"
print("Array d:\n" , e)

Array d:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
# Create an identity matrix
f = np.eye(4)       # 4x4 identity matrix
print("Indentity matrix f:\n" , f)

Indentity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [28]:
# Reshape an array
a1 = np.array([1,2,3])
reshape = np.reshape(a1, (1,3))     # Reshape to 1x3
print("Reshape array:" , reshape)

Reshape array: [[1 2 3]]


In [30]:
# Flatten an array
f1 = np.array([[1,2], [3,4]])
flattened = np.ravel(f1)    # ravel() converts a multi-dimensional array into a 1D array.
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [31]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Converting rows into columns and columns into rows.
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [32]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically (stacks arrays row-wise (one below another).)
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# 3. Mathematical Functions

In [36]:
# Add two arrays
g = np.array([1,2,3,4])
added = np.add(g,2)  # np.add = used to perform element-wise addition. 

    #   [1,2,3,4]
    # + [2,2,2,2]
    #  --------------
    #   [3,4,5,6]

print("Assed 2 to g:", added)

Assed 2 to g: [3 4 5 6]


In [42]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

        # 1² = 1
        # 2² = 4
        # 3² = 9
        # 4² = 16


Squared g: [ 1  4  9 16]


In [43]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [44]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [45]:
# Dot product of two arrays
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, g)  # Dot product of a and g
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [46]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [47]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.add(a,b))

        # 1+4 = 5
        # 2+5 = 7
        # 3+6 = 9


[5 7 9]


# 4. Statistical Functions

In [50]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Meanof s:" , mean)

# mean = sum of all element / number of element = 1+2+3+4/4 = 10/4 = 2.5

Meanof s: 2.5


In [51]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [52]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [55]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


# 5. Linear Algebra Functions

In [56]:
# Create a matrix
matrix = np.array([[1,2], [3,4]])


In [ ]:
# 🔹 Formula for 2×2 Matrix   =    det=(a×d)−(b×c)# 

In [58]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:" , determinant)

# (1×4)−(2×3) = 4−6=−2

Determinant of matrix: -2.0000000000000004


In [ ]:
        #  np.linalg.inv() (Inverse)
        #  np.linalg.eig() (Eigenvalues)
        #  np.dot() (Matrix multiplication)

In [61]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

# 1/ -2 [ 4  2
#        −3  1 ]

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [62]:
#🔹 Formula for 2×2 Inverse  = 1 / ad-bc[ d −b​ 
#                                        −c a​]

# 6. Random Sampling Functions

In [64]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print("Random values:" , random_vals)

Random values: [0.03723577 0.21699609 0.70524847]


In [65]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [66]:
# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [67]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7 Boolean & Logical Functions

In [70]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [71]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [72]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [73]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


# 8. Set Operations

In [74]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [75]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9. Array Attribute Functions

In [76]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# 10. Other Functions

In [77]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [78]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [79]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
